package errmsg

const (
	SUCCESS = 200
	ERROR   = 500

	ERROR_USERID_USED    = 1001
	ERROR_USER_NOT_EXIST = 1003
	ERROR_PASSWORD_WRONG = 1004
	ERROR_USER_NOT_RIGHT = 1005

	ERROR_TOKEN_EXIST = 1006
	ERROR_USERID_NULL = 1007

	ERROR_USER_IS_SIGNIN = 1008

	ERROR_POST_FAIL = 1009

	ERROR_USER_IS_LEAVING = 1010

	ERROR_UPDATE_FAIL    = 1011
	ERROR_TOEXAMINE_FAIL = 1012
	ERROR_DELETE_FAIL    = 1013

	ERROR_REPORT_IS_BEING_WIRRTRE  = 1014
	ERROR_WORKLOG_IS_BEING_WIRRTRE = 1015
	ERROR_IT_IS_BEING_WIRRTRE      = 1017
	ERROR_STATION_IS_BEING_WIRRTRE = 1018
	ERROR_USER_NOT_CHARGE_FOR_IT   = 1019
	ERROR_Check_FAIL               = 1020
	ERROR_TOKEN_NOT_EXIST          = 1021
)

var codeMsg = map[int]string{
	SUCCESS: "OK",
	ERROR:   "Fail",

	ERROR_USERID_USED:    "账号已被使用",
	ERROR_USER_NOT_EXIST: "用户不存在",
	ERROR_PASSWORD_WRONG: "密码错误",
	ERROR_USER_NOT_RIGHT: "用户权限不足",
	ERROR_USERID_NULL:    "获取用户名为空",

	ERROR_TOKEN_EXIST:     "Token已存在",
	ERROR_USER_IS_SIGNIN:  "用户已签到",
	ERROR_TOKEN_NOT_EXIST: "Token不存在",

	ERROR_POST_FAIL: "提交失败",

	ERROR_USER_IS_LEAVING: "用户已在本日提交请假申请",

	ERROR_UPDATE_FAIL:    "更新信息失败",
	ERROR_TOEXAMINE_FAIL: "审核失败",
	ERROR_DELETE_FAIL:    "删除失败",
	ERROR_Check_FAIL:     "查找失败",

	ERROR_REPORT_IS_BEING_WIRRTRE:  "你已撰写过此标题的实习报告",
	ERROR_WORKLOG_IS_BEING_WIRRTRE: "你已撰写过此天的工作日志报告",
	ERROR_IT_IS_BEING_WIRRTRE:      "该学生成绩已经录入过了",
	ERROR_STATION_IS_BEING_WIRRTRE: "此公司岗位已经在列表中",
	ERROR_USER_NOT_CHARGE_FOR_IT:   "此用户不负责此公司的企业需求",
}

func GetErrMsg(code int) string {
	return codeMsg[code]
}
